name: brics_social
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  rxdart: ^0.27.7
  bloc: ^8.1.1
  dio: ^5.0.3
  get_it: ^7.2.0
  shared_preferences: ^2.0.20
  equatable: ^2.0.5
  injectable: ^2.1.0
  app_kit: 
    git:
        url: https://github.com/KerJen/app_kit.git
  easy_localization: ^3.0.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  auto_route: ^5.0.4
  dartz: ^0.10.1
  mask_text_input_formatter: ^2.4.0
  flutter_tags: ^1.0.0-nullsafety.1
  http_status_code: ^0.0.2
  flutter_styled_toast: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  build_runner: ^2.3.3
  injectable_generator: ^2.1.4
  auto_route_generator: ^5.0.3
  

flutter:
  uses-material-design: true

  assets:
    - assets/i10n/
