name: brics_social
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  injectable: ^2.1.0
  app_kit: 
    git:
        url: https://github.com/KerJen/app_kit.git
  freezed_annotation: ^2.2.0
  auto_route: ^5.0.4
  dartz: ^0.10.1
  mask_text_input_formatter: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  auto_route_generator: ^5.0.3
  

flutter:
  uses-material-design: true
